var users = {
        'gbenhatchi@hotmail.fr':{
            'id':'u0',
            'email':'gbenhatchi@hotmail.fr',
            'mdp':'0000',
            'fname':'Benhatchi',
            'name':'Moukhtar',
            'age':22,
            'friends':{
              'ids':[
                'bahri.aimen48@gmail.com',
                'kissi@mail.com'
              ],
              'allows':[
                true,
                true
              ]
            },
            'groups':['g1'],
            'icon':'benhatchi.jpg',
            'is_logged':false
        },
        'bahri.aimen48@gmail.com':{
            'id':'u1',
            'email':'bahri.aimen48@gmail.com',
            'mdp':'1111',
            'fname':'Bahri',
            'name':'Aimene',
            'age':23,
            'friends':{
              'ids':[
                "gbenhatchi@hotmail.fr",
                "kissi@mail.com",
                "test.mail.com"
              ],
              'allows':[
                true,
                true,
                true
              ]
            },
            'groups':['g1'],
            'icon':'bahri.jpg',
            'is_logged':false
        },
        'kissi@mail.com':{
            'id':'u2',
            'email':'kissi@mail.com',
            'mdp':'2222',
            'fname':'Kissi',
            'name':'Nazim',
            'age':22,
            'friends':{
              'ids':[
                'gbenhatchi@hotmail.fr',
                'bahri.aimen48@gmail.com'
              ],
              'allows':[
                true,
                true
              ]
            },
            'groups':['g1'],
            'icon':'',
            'is_logged':false
        },
        'test.mail.com':{
            'id':'u3',
            'email':'test.mail.com',
            'mdp':'3333',
            'fname':'Banana',
            'name':'Abidawi',
            'age':45,
            'friends':{
              'ids':[
                'bahri.aimen48@gmail.com'
              ],
              'allows':[
                true
              ]
            },
            'groups':[

            ],
            'icon':'',
            'is_logged':false
        }

}

module.exports = {
  users : users
};
